# Site Info
<<<<<<< HEAD
title: Ming's devlog
=======
title: Ming's Blog
>>>>>>> d19e8a8b6a788f03679ec3b5f45aeca35cec0277
tagline: 
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: https://github.com/mumuming
logo: ''
content: 

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: myunghwaKim
  description: A passionate <strong>developer</strong>
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    github:    https://github.com/mumuming
    #facebook:  <hide>
    email: mailto:mh10041214@gmail.com   

# Navigation (2nd level links supported)
nav:
  Post:
    - '/blog/' 
  Categories:           
    # - { Categories All: '/blog/categories/' }
    - '/'
    - { TIL: '/blog/categories/#til' }
    - { Java: '/blog/categories/#java' }
    #- { Project: '/blog/categories/#project' }
  About:
    - '/about/' 
# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: '/public/img/funny_moment.png'

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-143016338-1' # leave blank if you don't want google analytics
disqus_short_name: 'mumuming-github-io' # leave blank if you don't want disqus

